apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: test-nodejs
build:
  artifacts:
    - image: my-image
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - deployment.yaml
